// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NordiskaPortal.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NordiskaPortal.Api.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20260924075947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NordiskaPortal.Api.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Storgatan 1, 111 22 Stockholm",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "anna@example.com",
                            Name = "Anna Lindqvist",
                            PasswordHash = "$2b$12$hg6bJTmUyy.QTahIR9LWf.6vdXcGceKXaMd0r4mOeVbyvAAeX8vEO",
                            PersonalId = "19850505-1234"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Kungsgatan 5, 411 19 Göteborg",
                            CreatedAt = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "erik@example.com",
                            Name = "Erik Johansson",
                            PasswordHash = "$2b$12$hg6bJTmUyy.QTahIR9LWf.6vdXcGceKXaMd0r4mOeVbyvAAeX8vEO",
                            PersonalId = "19991212-5678"
                        });
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.FaqEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("FaqEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Räntan beräknas och sätts in på ditt sparkonto vid årets slut (den 31 december).",
                            Category = "Ränta",
                            Keywords = new[] { "ränta", "utbetalning", "när", "betalas", "årlig" },
                            Question = "När betalas räntan ut?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Uttag görs via appen under 'Mina konton'. Uttaget bokförs normalt inom två bankdagar.",
                            Category = "Transaktioner",
                            Keywords = new[] { "uttag", "ta ut", "pengar", "överföring" },
                            Question = "Hur gör jag ett uttag?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Din årsrapport (skatteunderlag) finns under 'Mina rapporter' när den har skapats för aktuellt år.",
                            Category = "Rapporter",
                            Keywords = new[] { "årsrapport", "rapport", "skatt", "deklaration" },
                            Question = "Var hittar jag min årsrapport?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Kontakta kundservice eller ansök direkt i appen under 'Nytt konto' för att öppna ett nytt sparkonto.",
                            Category = "Konto",
                            Keywords = new[] { "öppna", "nytt", "sparkonto", "konto", "ansök" },
                            Question = "Hur öppnar jag ett nytt sparkonto?"
                        });
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.SavingsAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("SavingsAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "NKM-10001",
                            AccountType = "Savings",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            InterestRate = 0.0350m
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "NKM-10002",
                            AccountType = "Savings",
                            CreatedAt = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            InterestRate = 0.0280m
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "NKM-20001",
                            AccountType = "Savings",
                            CreatedAt = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            InterestRate = 0.0350m
                        });
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.SavingsGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TargetAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CustomerId");

                    b.ToTable("SavingsGoals");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.TaxReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PdfData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Year")
                        .IsUnique();

                    b.ToTable("TaxReports");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Amount = 125000.00m,
                            Description = "Lön",
                            PostingDate = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deposit"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Amount = 45000.00m,
                            Description = "Swish",
                            PostingDate = new DateTime(2026, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2026, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deposit"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Amount = 89500.00m,
                            Description = "Lön",
                            PostingDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2026, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deposit"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 1,
                            Amount = 89500.00m,
                            Description = "Swish",
                            PostingDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deposit"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 1,
                            Amount = 40500.00m,
                            Description = "Lön",
                            PostingDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2025, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deposit"
                        },
                        new
                        {
                            Id = 6,
                            AccountId = 1,
                            Amount = 20000.00m,
                            Description = "Semester",
                            PostingDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Withdrawal"
                        },
                        new
                        {
                            Id = 7,
                            AccountId = 1,
                            Amount = 50000.00m,
                            Description = "Lön",
                            PostingDate = new DateTime(2023, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TransactionDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Type = "Deposit"
                        });
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.RefreshToken", b =>
                {
                    b.HasOne("NordiskaPortal.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.SavingsAccount", b =>
                {
                    b.HasOne("NordiskaPortal.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.SavingsGoal", b =>
                {
                    b.HasOne("NordiskaPortal.Api.Models.SavingsAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.HasOne("NordiskaPortal.Api.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.TaxReport", b =>
                {
                    b.HasOne("NordiskaPortal.Api.Models.SavingsAccount", "SavingsAccount")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsAccount");
                });

            modelBuilder.Entity("NordiskaPortal.Api.Models.Transaction", b =>
                {
                    b.HasOne("NordiskaPortal.Api.Models.SavingsAccount", "SavingsAccount")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavingsAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
