#!/usr/bin/env python3
"""Usage: python3 tools/gen_logo.py nordiska.png src/assets/logo_data.c"""
import sys
from PIL import Image

src, dst = sys.argv[1], sys.argv[2]
img = Image.open(src).convert("RGBA")

bbox = img.getchannel("A").getbbox()          # trim transparent margins
if bbox:
    img = img.crop(bbox)

bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
rgb = Image.alpha_composite(bg, img).convert("RGB")
w, h = rgb.size
data = rgb.tobytes()

with open(dst, "w") as f:
    f.write("/* Generated by tools/gen_logo.py - do not edit. */\n")
    f.write('#include "assets/logo_data.h"\n\n')
    f.write(f"const unsigned int LOGO_WIDTH = {w};\n")
    f.write(f"const unsigned int LOGO_HEIGHT = {h};\n\n")
    f.write("const unsigned char LOGO_RGB[] = {\n")
    for i in range(0, len(data), 16):
        f.write("    " + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",\n")
    f.write("};\n")
print(f"{w}x{h}, {len(data)} bytes")
